# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FishingPoint' do
  use_frameworks!

  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage'
  pod 'HPGradientLoading'

end
